version: '3'
services:
  registrator:
    image: gliderlabs/registrator:latest
    container_name: registrator
    network_mode: host
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: "-cleanup=true -ip ${HOST_IP} consul://consul.service.consul:8500"
