version: '3'
services:
  dns:
    image: strm/dnsmasq
    container_name: dnsmasq
    volumes:
      - ./config/dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    entrypoint:
        - dnsmasq
        - "-d"

