version: '3'

services:
  postgres:
      image: postgres
      container_name: postgres
      volumes:
        - ./postgres/postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_DB=keycloak
        - POSTGRES_USER=keycloak
        - POSTGRES_PASSWORD=111111
        - SERVICE_NAME=postgres
        - SERVICE_TAGS=postgres
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    volumes:
        - ./postgres/postgres_data:/var/lib/postgresql/data/
    environment:
        - SERVICE_NAME=keycloak
        - SERVICE_TAGS=keycloak
        - SERVICE_8080_NAME=keycloak
        - DB_VENDOR=POSTGRES
        - DB_ADDR=postgres
        - DB_DATABASE=keycloak
        - DB_USER=keycloak
        - DB_SCHEMA=public
        - DB_PASSWORD=111111
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=admin
        - PROXY_ADDRESS_FORWARDING=true
    restart: unless-stopped
    ports:
      - '8180:8080'
    depends_on:
      - "postgres"
