version: '3'
services:
  nginx_proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: unless-stopped
    volumes:
      - ./config/:/etc/nginx/conf.d/
    environment:
      - SERVICE_80_NAME=medvedkama
      - SERVICE_TAGS=nginx-p
    ports:
      - 80:80
