global:
  scrape_interval: 5s
  external_labels:
    monitor: 'prakash-monitor'
scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['localhost:9090']

  - job_name: 'application1'

    metrics_path: '/metrics/application'
    static_configs:
      - targets: ['192.168.122.19:8080']  
